"""
SSH CA setup scripts — Windows PowerShell variants.
"""


def _user_ca_script_windows(pub_key, ca_label):
    # PowerShell single-quoted strings preserve everything literally except '' (escaped quote).
    # Escape any single quote in the public key for safety.
    ps_pub_key = pub_key.replace("'", "''")
    ps_label = ca_label.replace("'", "''")
    return rf'''<#
.SYNOPSIS
    SSH User CA Trust Setup Script (Windows OpenSSH Server)
    CA: {ca_label}
    Generated by UCM (Ultimate Certificate Manager)

.DESCRIPTION
    Configures the Windows OpenSSH Server (sshd) to trust user certificates
    signed by the above CA. Writes the CA public key to ProgramData\\ssh\\ssh_ca_keys
    and adds TrustedUserCAKeys + AuthorizedPrincipalsFile directives to sshd_config.

    Run from an elevated PowerShell prompt.

.PARAMETER DryRun
    Preview what would change without modifying any file or service.

.PARAMETER NonInteractive
    Skip all prompts (OpenSSH install, end pause). Use in CI/automation.

.PARAMETER NoPause
    Do not pause at the end (default is to pause so the window stays open).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\\ssh_ca_setup.ps1
    powershell -ExecutionPolicy Bypass -File .\\ssh_ca_setup.ps1 -DryRun
    powershell -ExecutionPolicy Bypass -File .\\ssh_ca_setup.ps1 -NonInteractive -NoPause
#>

[CmdletBinding()]
param(
    [switch]$DryRun,
    [switch]$NonInteractive,
    [switch]$NoPause
)

$ErrorActionPreference = 'Stop'

# --- Helpers ---
function Write-Info  ($msg) {{ Write-Host "[INFO]  $msg" -ForegroundColor Cyan }}
function Write-Ok    ($msg) {{ Write-Host "[OK]    $msg" -ForegroundColor Green }}
function Write-Warn2 ($msg) {{ Write-Host "[WARN]  $msg" -ForegroundColor Yellow }}
function Write-Err   ($msg) {{ Write-Host "[ERROR] $msg" -ForegroundColor Red }}

function Pause-IfInteractive {{
    param([string]$Message = 'Press Enter to close this window...')
    if ($NoPause -or $NonInteractive) {{ return }}
    try {{ Read-Host -Prompt $Message | Out-Null }} catch {{ Start-Sleep -Seconds 30 }}
}}

# --- Transcript log (always-on so output survives even if window closes) ---
$LogFile = Join-Path $env:TEMP ("ucm_ssh_user_ca_setup_" + (Get-Date -Format 'yyyyMMdd_HHmmss') + ".log")
try {{ Start-Transcript -Path $LogFile -Force | Out-Null }} catch {{ }}
Write-Host "Log file: $LogFile" -ForegroundColor DarkGray

$ScriptFailed = $false
try {{

# --- Configuration ---
$SshDir         = Join-Path $env:ProgramData 'ssh'
$CaKeyDir       = Join-Path $SshDir 'ssh_ca_keys'
$CaKeyFile      = Join-Path $CaKeyDir 'user_ca.pub'
$SshdConfig     = Join-Path $SshDir 'sshd_config'
$PrincipalsDir  = Join-Path $SshDir 'auth_principals'

# --- Admin check ---
$identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
    Write-Err "This script must be run as Administrator."
    Write-Info "Right-click PowerShell -> Run as Administrator, then re-run this script."
    throw "Not running as Administrator"
}}

Write-Host "========================================" -ForegroundColor White
Write-Host "SSH User CA Trust Setup (Windows)"      -ForegroundColor White
Write-Host "CA: {ca_label}"
if ($DryRun) {{
    Write-Host ">>> DRY RUN - no changes will be made <<<" -ForegroundColor Yellow
}}
Write-Host "========================================" -ForegroundColor White
Write-Host ""

# --- Pre-flight: detect existing OpenSSH Server install (FoD or winget) ---
$sshdSvc = Get-Service -Name sshd -ErrorAction SilentlyContinue
$fodInstalled = $false
$wingetInstalled = $false
try {{
    $cap = Get-WindowsCapability -Online -Name 'OpenSSH.Server~~~~0.0.1.0' -ErrorAction SilentlyContinue
    if ($cap -and $cap.State -eq 'Installed') {{ $fodInstalled = $true }}
}} catch {{ }}
$wingetSshdPath = Join-Path $env:ProgramFiles 'OpenSSH\sshd.exe'
if (Test-Path $wingetSshdPath) {{ $wingetInstalled = $true }}

if ($fodInstalled) {{
    Write-Info "Detected OpenSSH Server install: Windows Features-on-Demand"
    Write-Info "  Binary: $env:WINDIR\System32\OpenSSH\sshd.exe"
}}
if ($wingetInstalled) {{
    Write-Info "Detected OpenSSH Server install: winget / standalone"
    Write-Info "  Binary: $wingetSshdPath"
}}
Write-Info "CA public key will be installed to: $CaKeyFile"
Write-Info "sshd_config will be updated at:    $SshdConfig"

if (-not ($fodInstalled -or $wingetInstalled -or $sshdSvc)) {{
    Write-Warn2 "OpenSSH Server is not installed (neither FoD nor winget detected)."
    $doInstall = $false
    if ($DryRun) {{
        Write-Info "Would offer to install OpenSSH.Server via Features-on-Demand (skipped in -DryRun)."
    }} elseif ($NonInteractive) {{
        Write-Err "OpenSSH Server is missing and -NonInteractive was supplied."
        Write-Info "Install manually with one of:"
        Write-Info "  Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"
        Write-Info "  winget install Microsoft.OpenSSH.Beta"
        Write-Info "Then: Set-Service -Name sshd -StartupType 'Automatic'; Start-Service sshd"
        throw "OpenSSH Server missing"
    }} else {{
        $resp = Read-Host "Install OpenSSH Server via Features-on-Demand now? [Y/n]"
        if ($resp -eq '' -or $resp -match '^[Yy]') {{ $doInstall = $true }}
    }}
    if ($doInstall) {{
        Write-Info "Installing OpenSSH.Server via Add-WindowsCapability (this may take 1-2 minutes)..."
        try {{
            Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction Stop | Out-Null
        }} catch {{
            $errMsg = $_.Exception.Message
            Write-Err "Add-WindowsCapability failed: $errMsg"
            Write-Host ""
            Write-Host "---- Diagnostic ----" -ForegroundColor Yellow
            if ($errMsg -match '0x8024500c|WU_E_PT_WMT_MISSING') {{
                Write-Host "Cause: 0x8024500c (WU_E_PT_WMT_MISSING)" -ForegroundColor Yellow
                Write-Host "  This machine is configured to use WSUS (group policy), but the WSUS server"
                Write-Host "  does not host the OpenSSH Features-on-Demand source, so Windows refuses to"
                Write-Host "  download it from Microsoft Update."
            }} elseif ($errMsg -match '0x800f0954') {{
                Write-Host "Cause: 0x800f0954 (CBS_E_INVALID_WINDOWS_UPDATE_COUNT_WSUS)" -ForegroundColor Yellow
                Write-Host "  Group policy forbids reaching Microsoft Update for Features-on-Demand."
            }} elseif ($errMsg -match '0x80240438|0x8024402c|0x80072ee2|0x80072efd') {{
                Write-Host "Cause: Windows Update / WSUS connectivity error ($errMsg)" -ForegroundColor Yellow
                Write-Host "  The Windows Update client cannot reach its configured update source."
            }} else {{
                Write-Host "Cause: see error message above." -ForegroundColor Yellow
            }}
            $regAU = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'
            $useWUServer = (Get-ItemProperty -Path $regAU -Name UseWUServer -ErrorAction SilentlyContinue).UseWUServer
            $wuServer = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name WUServer -ErrorAction SilentlyContinue).WUServer
            if ($useWUServer -eq 1) {{
                Write-Host ("  Detected WSUS policy: UseWUServer=1, WUServer={0}" -f $wuServer)
            }} else {{
                Write-Host "  No WSUS policy detected (UseWUServer != 1)."
            }}
            Write-Host ""
            Write-Host "Resolution options (ask your Windows / AD team — do NOT bypass policy yourself):" -ForegroundColor Cyan
            Write-Host "  1. Ask the WSUS admin to approve the OpenSSH FoD package, OR enable the policy"
            Write-Host "     'Specify settings for optional component installation and component repair'"
            Write-Host "     with 'Download repair content ... directly from Windows Update' enabled"
            Write-Host "     (Computer Config > Admin Templates > System)."
            Write-Host "  2. Install offline from a Features-on-Demand ISO matching this Windows build:"
            Write-Host "     Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -Source <FoD-ISO>\LanguagesAndOptionalFeatures"
            Write-Host "  3. Install OpenSSH Server manually via Settings > Apps > Optional features."
            Write-Host "Re-run this script once OpenSSH Server is installed and running."
            Write-Host "--------------------" -ForegroundColor Yellow
            throw
        }}
        Set-Service -Name sshd -StartupType 'Automatic'
        Start-Service sshd
        if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {{
            try {{
                New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
                    -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 | Out-Null
                Write-Ok "Firewall rule added (TCP/22 inbound)"
            }} catch {{
                Write-Warn2 "Could not create firewall rule: $_"
            }}
        }}
        $sshdSvc = Get-Service -Name sshd
        Write-Ok "OpenSSH Server installed and started"
    }} elseif (-not $DryRun) {{
        throw "OpenSSH Server is required. Install it and re-run this script."
    }}
}} elseif ($sshdSvc) {{
    Write-Info "sshd service detected (status: $($sshdSvc.Status))"
}} else {{
    Write-Warn2 "OpenSSH binaries detected but sshd service is not registered."
    Write-Info "Run: Set-Service -Name sshd -StartupType 'Automatic'; Start-Service sshd"
}}

# --- Step 1: Create CA key directory ---
Write-Info "Creating CA key directory: $CaKeyDir"
if ($DryRun) {{
    if (Test-Path $CaKeyDir) {{ Write-Ok "Directory already exists" }} else {{ Write-Info "Would create: $CaKeyDir" }}
}} else {{
    New-Item -ItemType Directory -Path $CaKeyDir -Force | Out-Null
    Write-Ok "Directory ready: $CaKeyDir"
}}

# --- Step 2: Write CA public key ---
$CaPubKey = @'
{ps_pub_key}
'@

Write-Info "Writing CA public key to: $CaKeyFile"
if ($DryRun) {{
    if (Test-Path $CaKeyFile) {{
        $existing = Get-Content $CaKeyFile -Raw -ErrorAction SilentlyContinue
        if ($existing.Trim() -eq $CaPubKey.Trim()) {{
            Write-Ok "Key file already contains the correct key"
        }} else {{
            Write-Warn2 "Would overwrite existing key file"
        }}
    }} else {{
        Write-Info "Would create: $CaKeyFile"
    }}
}} else {{
    Set-Content -Path $CaKeyFile -Value $CaPubKey -Encoding ASCII -NoNewline:$false
    # Lock down ACL: SYSTEM + Administrators full, no inheritance, no Everyone
    $acl = Get-Acl $CaKeyFile
    $acl.SetAccessRuleProtection($true, $false)
    $acl.Access | ForEach-Object {{ [void]$acl.RemoveAccessRule($_) }}
    $rules = @(
        New-Object System.Security.AccessControl.FileSystemAccessRule('NT AUTHORITY\\SYSTEM','FullControl','Allow'),
        New-Object System.Security.AccessControl.FileSystemAccessRule('BUILTIN\\Administrators','FullControl','Allow')
    )
    foreach ($r in $rules) {{ $acl.AddAccessRule($r) }}
    Set-Acl -Path $CaKeyFile -AclObject $acl
    Write-Ok "CA public key written"
}}

# --- Step 3: Back up sshd_config ---
if (-not (Test-Path $SshdConfig)) {{
    Write-Err "sshd_config not found at $SshdConfig"
    exit 1
}}
$backup = "$SshdConfig.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
Write-Info "Backing up sshd_config to: $backup"
if ($DryRun) {{
    Write-Info "Would create backup: $backup"
}} else {{
    Copy-Item -Path $SshdConfig -Destination $backup
    Write-Ok "Backup created"
}}

# --- Step 4: Add TrustedUserCAKeys directive ---
Write-Info "Checking sshd_config for TrustedUserCAKeys directive..."
$existingConfig = Get-Content $SshdConfig -Raw
if ($existingConfig -match '(?m)^\\s*TrustedUserCAKeys\\b') {{
    Write-Warn2 "TrustedUserCAKeys is already configured. Skipping - verify path is correct."
}} else {{
    if ($DryRun) {{
        Write-Info "Would append to ${{SshdConfig}}:"
        Write-Info "  TrustedUserCAKeys $CaKeyFile"
    }} else {{
        Add-Content -Path $SshdConfig -Value ""
        Add-Content -Path $SshdConfig -Value "# SSH User CA Trust - added by UCM setup script"
        Add-Content -Path $SshdConfig -Value "TrustedUserCAKeys $CaKeyFile"
        Write-Ok "Added TrustedUserCAKeys directive"
    }}
}}

# --- Step 5: AuthorizedPrincipalsFile directory ---
Write-Info "Setting up AuthorizedPrincipalsFile directory: $PrincipalsDir"
if (-not $DryRun) {{
    New-Item -ItemType Directory -Path $PrincipalsDir -Force | Out-Null
    Write-Ok "Principals directory ready"
}}

if ($existingConfig -match '(?m)^\\s*AuthorizedPrincipalsFile\\b') {{
    Write-Warn2 "AuthorizedPrincipalsFile already configured. Skipping."
}} else {{
    if ($DryRun) {{
        Write-Info "Would append: AuthorizedPrincipalsFile $PrincipalsDir\\%u"
    }} else {{
        Add-Content -Path $SshdConfig -Value "AuthorizedPrincipalsFile $PrincipalsDir\\%u"
        Write-Ok "Added AuthorizedPrincipalsFile directive"
    }}
}}

# --- Step 6: Validate sshd config ---
Write-Info "Validating sshd configuration (sshd -T)..."
$sshdExe = (Get-Command sshd.exe -ErrorAction SilentlyContinue).Source
if (-not $sshdExe) {{ $sshdExe = Join-Path $env:ProgramFiles 'OpenSSH\\sshd.exe' }}
if ($DryRun) {{
    Write-Info "Would run: sshd -T"
}} elseif (Test-Path $sshdExe) {{
    & $sshdExe -T 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {{
        Write-Ok "sshd configuration is valid"
    }} else {{
        Write-Err "sshd configuration test failed. Restoring backup..."
        Copy-Item -Path $backup -Destination $SshdConfig -Force
        Write-Err "Backup restored. Inspect sshd_config manually."
        exit 1
    }}
}} else {{
    Write-Warn2 "sshd.exe not found - skipping config validation"
}}

# --- Step 7: Restart sshd ---
Write-Info "Restarting sshd service..."
if ($DryRun) {{
    Write-Info "Would run: Restart-Service sshd"
}} else {{
    try {{
        Restart-Service -Name sshd -Force
        Write-Ok "sshd restarted successfully"
    }} catch {{
        Write-Warn2 "Restart-Service failed: $_  - check service status manually."
    }}
}}

Write-Host ""
Write-Host "========================================" -ForegroundColor White
if ($DryRun) {{
    Write-Host "Dry run complete - no changes were made." -ForegroundColor Yellow
}} else {{
    Write-Host "Setup complete!" -ForegroundColor Green
}}
Write-Host "========================================" -ForegroundColor White
Write-Host ""

if (-not $DryRun) {{
    Write-Info "Next steps:"
    Write-Info "  1. For each Windows user, create a principals file:"
    Write-Info "     Set-Content -Path '$PrincipalsDir\\<username>' -Value 'principal_name'"
    Write-Info "  2. Sign user keys with the CA in UCM (SSH > Certificates > Sign)"
    Write-Info "  3. Users can now log in with their signed certificate"
}}

}} catch {{
    $ScriptFailed = $true
    Write-Host ""
    Write-Err "Setup FAILED: $_"
    if ($_.ScriptStackTrace) {{
        Write-Host $_.ScriptStackTrace -ForegroundColor DarkGray
    }}
    Write-Host ""
    Write-Info "Full log saved to: $LogFile"
}} finally {{
    try {{ Stop-Transcript | Out-Null }} catch {{ }}
    Write-Host ""
    if ($ScriptFailed) {{
        Pause-IfInteractive 'An error occurred. Press Enter to close this window...'
        exit 1
    }} else {{
        Pause-IfInteractive
    }}
}}
'''


def _host_ca_script_windows(pub_key, ca_label, hostname):
    ps_pub_key = pub_key.replace("'", "''")
    ps_label = ca_label.replace("'", "''")
    hostname_init = hostname if hostname else ''
    return rf'''<#
.SYNOPSIS
    SSH Host CA Trust Setup Script (Windows OpenSSH Server)
    CA: {ca_label}
    Generated by UCM (Ultimate Certificate Manager)

.DESCRIPTION
    Configures the Windows OpenSSH Server to present a host certificate signed
    by the above CA. The host key signing itself must be performed via UCM
    (the CA private key is not exposed); this script prepares everything else
    and adds the HostCertificate directive once the cert is in place.

.PARAMETER DryRun
    Preview without modifying anything.

.PARAMETER NonInteractive
    Skip all prompts (OpenSSH install, end pause). Use in CI/automation.

.PARAMETER NoPause
    Do not pause at the end (default is to pause so the window stays open).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\\ssh_ca_setup.ps1
#>

[CmdletBinding()]
param(
    [switch]$DryRun,
    [switch]$NonInteractive,
    [switch]$NoPause
)

$ErrorActionPreference = 'Stop'

function Write-Info  ($msg) {{ Write-Host "[INFO]  $msg" -ForegroundColor Cyan }}
function Write-Ok    ($msg) {{ Write-Host "[OK]    $msg" -ForegroundColor Green }}
function Write-Warn2 ($msg) {{ Write-Host "[WARN]  $msg" -ForegroundColor Yellow }}
function Write-Err   ($msg) {{ Write-Host "[ERROR] $msg" -ForegroundColor Red }}

function Pause-IfInteractive {{
    param([string]$Message = 'Press Enter to close this window...')
    if ($NoPause -or $NonInteractive) {{ return }}
    try {{ Read-Host -Prompt $Message | Out-Null }} catch {{ Start-Sleep -Seconds 30 }}
}}

# --- Transcript log (always-on so output survives even if window closes) ---
$LogFile = Join-Path $env:TEMP ("ucm_ssh_host_ca_setup_" + (Get-Date -Format 'yyyyMMdd_HHmmss') + ".log")
try {{ Start-Transcript -Path $LogFile -Force | Out-Null }} catch {{ }}
Write-Host "Log file: $LogFile" -ForegroundColor DarkGray

$ScriptFailed = $false
try {{

# --- Configuration ---
$SshDir     = Join-Path $env:ProgramData 'ssh'
$CaKeyDir   = Join-Path $SshDir 'ssh_ca_keys'
$CaKeyFile  = Join-Path $CaKeyDir 'host_ca.pub'
$SshdConfig = Join-Path $SshDir 'sshd_config'
$Hostname   = '{hostname_init}'

# --- Admin check ---
$identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
    Write-Err "This script must be run as Administrator."
    Write-Info "Right-click PowerShell -> Run as Administrator, then re-run this script."
    throw "Not running as Administrator"
}}

if (-not $Hostname) {{
    try {{ $Hostname = [System.Net.Dns]::GetHostByName($env:COMPUTERNAME).HostName }} catch {{ $Hostname = $env:COMPUTERNAME }}
}}

Write-Host "========================================" -ForegroundColor White
Write-Host "SSH Host CA Trust Setup (Windows)"      -ForegroundColor White
Write-Host "CA:   {ca_label}"
Write-Host "Host: $Hostname"
if ($DryRun) {{
    Write-Host ">>> DRY RUN - no changes will be made <<<" -ForegroundColor Yellow
}}
Write-Host "========================================" -ForegroundColor White
Write-Host ""

$sshdSvc = Get-Service -Name sshd -ErrorAction SilentlyContinue
$fodInstalled = $false
$wingetInstalled = $false
try {{
    $cap = Get-WindowsCapability -Online -Name 'OpenSSH.Server~~~~0.0.1.0' -ErrorAction SilentlyContinue
    if ($cap -and $cap.State -eq 'Installed') {{ $fodInstalled = $true }}
}} catch {{ }}
$wingetSshdPath = Join-Path $env:ProgramFiles 'OpenSSH\sshd.exe'
if (Test-Path $wingetSshdPath) {{ $wingetInstalled = $true }}

if ($fodInstalled) {{
    Write-Info "Detected OpenSSH Server install: Windows Features-on-Demand"
    Write-Info "  Binary: $env:WINDIR\System32\OpenSSH\sshd.exe"
}}
if ($wingetInstalled) {{
    Write-Info "Detected OpenSSH Server install: winget / standalone"
    Write-Info "  Binary: $wingetSshdPath"
}}
Write-Info "CA public key will be installed to: $CaKeyFile"
Write-Info "sshd_config will be updated at:    $SshdConfig"

if (-not ($fodInstalled -or $wingetInstalled -or $sshdSvc)) {{
    Write-Warn2 "OpenSSH Server is not installed (neither FoD nor winget detected)."
    $doInstall = $false
    if ($DryRun) {{
        Write-Info "Would offer to install OpenSSH.Server via Features-on-Demand (skipped in -DryRun)."
    }} elseif ($NonInteractive) {{
        Write-Err "OpenSSH Server is missing and -NonInteractive was supplied."
        Write-Info "Install manually with one of:"
        Write-Info "  Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0"
        Write-Info "  winget install Microsoft.OpenSSH.Beta"
        throw "OpenSSH Server missing"
    }} else {{
        $resp = Read-Host "Install OpenSSH Server via Features-on-Demand now? [Y/n]"
        if ($resp -eq '' -or $resp -match '^[Yy]') {{ $doInstall = $true }}
    }}
    if ($doInstall) {{
        Write-Info "Installing OpenSSH.Server via Add-WindowsCapability (this may take 1-2 minutes)..."
        try {{
            Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction Stop | Out-Null
        }} catch {{
            $errMsg = $_.Exception.Message
            Write-Err "Add-WindowsCapability failed: $errMsg"
            Write-Host ""
            Write-Host "---- Diagnostic ----" -ForegroundColor Yellow
            if ($errMsg -match '0x8024500c|WU_E_PT_WMT_MISSING') {{
                Write-Host "Cause: 0x8024500c (WU_E_PT_WMT_MISSING)" -ForegroundColor Yellow
                Write-Host "  This machine is configured to use WSUS (group policy), but the WSUS server"
                Write-Host "  does not host the OpenSSH Features-on-Demand source, so Windows refuses to"
                Write-Host "  download it from Microsoft Update."
            }} elseif ($errMsg -match '0x800f0954') {{
                Write-Host "Cause: 0x800f0954 (CBS_E_INVALID_WINDOWS_UPDATE_COUNT_WSUS)" -ForegroundColor Yellow
                Write-Host "  Group policy forbids reaching Microsoft Update for Features-on-Demand."
            }} elseif ($errMsg -match '0x80240438|0x8024402c|0x80072ee2|0x80072efd') {{
                Write-Host "Cause: Windows Update / WSUS connectivity error ($errMsg)" -ForegroundColor Yellow
                Write-Host "  The Windows Update client cannot reach its configured update source."
            }} else {{
                Write-Host "Cause: see error message above." -ForegroundColor Yellow
            }}
            $regAU = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'
            $useWUServer = (Get-ItemProperty -Path $regAU -Name UseWUServer -ErrorAction SilentlyContinue).UseWUServer
            $wuServer = (Get-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate' -Name WUServer -ErrorAction SilentlyContinue).WUServer
            if ($useWUServer -eq 1) {{
                Write-Host ("  Detected WSUS policy: UseWUServer=1, WUServer={0}" -f $wuServer)
            }} else {{
                Write-Host "  No WSUS policy detected (UseWUServer != 1)."
            }}
            Write-Host ""
            Write-Host "Resolution options (ask your Windows / AD team — do NOT bypass policy yourself):" -ForegroundColor Cyan
            Write-Host "  1. Ask the WSUS admin to approve the OpenSSH FoD package, OR enable the policy"
            Write-Host "     'Specify settings for optional component installation and component repair'"
            Write-Host "     with 'Download repair content ... directly from Windows Update' enabled"
            Write-Host "     (Computer Config > Admin Templates > System)."
            Write-Host "  2. Install offline from a Features-on-Demand ISO matching this Windows build:"
            Write-Host "     Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -Source <FoD-ISO>\LanguagesAndOptionalFeatures"
            Write-Host "  3. Install OpenSSH Server manually via Settings > Apps > Optional features."
            Write-Host "Re-run this script once OpenSSH Server is installed and running."
            Write-Host "--------------------" -ForegroundColor Yellow
            throw
        }}
        Set-Service -Name sshd -StartupType 'Automatic'
        Start-Service sshd
        if (-not (Get-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -ErrorAction SilentlyContinue)) {{
            try {{
                New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
                    -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 | Out-Null
                Write-Ok "Firewall rule added (TCP/22 inbound)"
            }} catch {{
                Write-Warn2 "Could not create firewall rule: $_"
            }}
        }}
        $sshdSvc = Get-Service -Name sshd
        Write-Ok "OpenSSH Server installed and started"
    }} elseif (-not $DryRun) {{
        throw "OpenSSH Server is required. Install it and re-run this script."
    }}
}} elseif ($sshdSvc) {{
    Write-Info "sshd service detected (status: $($sshdSvc.Status))"
}} else {{
    Write-Warn2 "OpenSSH binaries detected but sshd service is not registered."
    Write-Info "Run: Set-Service -Name sshd -StartupType 'Automatic'; Start-Service sshd"
}}

# --- Step 1: Create CA key directory ---
if (-not $DryRun) {{
    New-Item -ItemType Directory -Path $CaKeyDir -Force | Out-Null
    Write-Ok "CA key directory ready: $CaKeyDir"
}}

# --- Step 2: Write CA public key ---
$CaPubKey = @'
{ps_pub_key}
'@

if (-not $DryRun) {{
    Set-Content -Path $CaKeyFile -Value $CaPubKey -Encoding ASCII -NoNewline:$false
    Write-Ok "CA public key written: $CaKeyFile"
}} else {{
    Write-Info "Would write CA public key to: $CaKeyFile"
}}

# --- Step 3: Backup sshd_config ---
if (-not (Test-Path $SshdConfig)) {{ Write-Err "sshd_config not found at $SshdConfig"; exit 1 }}
$backup = "$SshdConfig.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
if (-not $DryRun) {{ Copy-Item $SshdConfig $backup; Write-Ok "Backup: $backup" }} else {{ Write-Info "Would back up to: $backup" }}

# --- Step 4: Locate a host key ---
$hostKey = $null
foreach ($kt in @('ed25519','ecdsa','rsa')) {{
    $candidate = Join-Path $SshDir "ssh_host_${{kt}}_key.pub"
    if (Test-Path $candidate) {{
        $hostKey = Join-Path $SshDir "ssh_host_${{kt}}_key"
        break
    }}
}}
if (-not $hostKey) {{
    Write-Err "No SSH host key found in $SshDir."
    Write-Info "Generate with: ssh-keygen -A"
    exit 1
}}
$certFile = "$hostKey-cert.pub"
Write-Info "Found host key: $hostKey"

if (Test-Path $certFile) {{
    Write-Warn2 "Host certificate already exists: $certFile"
    Write-Warn2 "If you want to re-sign, remove it first and re-run this script."
}} else {{
    Write-Host ""
    Write-Warn2 "Host key signing requires the CA private key, which is managed by UCM."
    Write-Info "Sign via UCM:"
    Write-Info "  1. Copy the host public key to a workstation: $hostKey.pub"
    Write-Info "  2. UCM > SSH > Certificates > Sign Host Key"
    Write-Info "  3. Principals: $Hostname"
    Write-Info "  4. Place the resulting cert at: $certFile"
    Write-Host ""
}}

# --- Step 5: Add HostCertificate directive ---
$existingConfig = Get-Content $SshdConfig -Raw
if ($existingConfig -match '(?m)^\\s*HostCertificate\\b') {{
    Write-Warn2 "HostCertificate is already configured. Skipping."
}} else {{
    if ($DryRun) {{
        Write-Info "Would append: HostCertificate $certFile"
    }} else {{
        Add-Content -Path $SshdConfig -Value ""
        Add-Content -Path $SshdConfig -Value "# SSH Host Certificate - added by UCM setup script"
        Add-Content -Path $SshdConfig -Value "HostCertificate $certFile"
        Write-Ok "Added HostCertificate directive"
    }}
}}

# --- Step 6: Validate ---
$sshdExe = (Get-Command sshd.exe -ErrorAction SilentlyContinue).Source
if (-not $sshdExe) {{ $sshdExe = Join-Path $env:ProgramFiles 'OpenSSH\\sshd.exe' }}
if (-not $DryRun -and (Test-Path $sshdExe)) {{
    & $sshdExe -T 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {{
        Write-Ok "sshd configuration is valid"
    }} else {{
        Write-Err "sshd configuration test failed. Restoring backup..."
        Copy-Item $backup $SshdConfig -Force
        exit 1
    }}
}}

# --- Step 7: Restart sshd if cert is in place ---
if (-not $DryRun) {{
    if (Test-Path $certFile) {{
        try {{ Restart-Service -Name sshd -Force; Write-Ok "sshd restarted" }} catch {{ Write-Warn2 "sshd restart failed: $_" }}
    }} else {{
        Write-Warn2 "Skipping sshd restart - host certificate not present yet."
        Write-Warn2 "Sign the host key in UCM, place the cert, then: Restart-Service sshd"
    }}
}}

Write-Host ""
Write-Host "========================================" -ForegroundColor White
if ($DryRun) {{
    Write-Host "Dry run complete - no changes were made." -ForegroundColor Yellow
}} else {{
    Write-Host "Setup complete!" -ForegroundColor Green
}}
Write-Host "========================================" -ForegroundColor White
Write-Host ""

Write-Info "Clients should add to their known_hosts:"
Write-Info "  @cert-authority * <CA public key from $CaKeyFile>"

}} catch {{
    $ScriptFailed = $true
    Write-Host ""
    Write-Err "Setup FAILED: $_"
    if ($_.ScriptStackTrace) {{
        Write-Host $_.ScriptStackTrace -ForegroundColor DarkGray
    }}
    Write-Host ""
    Write-Info "Full log saved to: $LogFile"
}} finally {{
    try {{ Stop-Transcript | Out-Null }} catch {{ }}
    Write-Host ""
    if ($ScriptFailed) {{
        Pause-IfInteractive 'An error occurred. Press Enter to close this window...'
        exit 1
    }} else {{
        Pause-IfInteractive
    }}
}}
'''
